version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins #intially
    image: jenkins-ansible #later ansible installed within jenkins via new docker file
    build:
      context: jenkins-ansible #new folder created cosist new dockerfile which installs ansible within jenkins
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
     context: centos
    networks:
      - net
networks:
  net:
